// Write dist/client/_headers after the build.
//
// Each prerendered page gets a Content Security Policy that permits its own inline scripts by SHA-256 hash,
// and no other inline script. Cloudflare applies _headers to static assets, which includes prerendered pages.
// The builder and viewer handle player data, so the policy permits no network destination except this site.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const CLIENT_DIR = "dist/client";
const INLINE_SCRIPT = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g;

function htmlFiles(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) return htmlFiles(path);
    return name.endsWith(".html") ? [path] : [];
  });
}

// A browser hashes the script text after HTML parsing, not the bytes in the file.
// The parser changes line endings to LF, and changes each NUL character to U+FFFD.
// TanStack Start puts NUL characters in its hydration script, so this step is necessary.
function asParsed(script) {
  return script.replace(/\r\n?/g, "\n").replaceAll("\u0000", "\uFFFD");
}

function policy(hashes) {
  const scriptSources = ["'self'", ...hashes.map((hash) => `'sha256-${hash}'`)].join(" ");
  return [
    "default-src 'self'",
    `script-src ${scriptSources}`,
    "style-src 'self'",
    "img-src 'self' data:",
    "font-src 'self'",
    "connect-src 'self'",
    "frame-src https://tally.so",
    "object-src 'none'",
    "base-uri 'none'",
    "form-action 'none'",
    "frame-ancestors 'none'",
  ].join("; ");
}

const rules = [];
for (const file of htmlFiles(CLIENT_DIR).sort()) {
  const html = readFileSync(file, "utf8");
  const hashes = [...html.matchAll(INLINE_SCRIPT)]
    .map((match) => match[1])
    .filter((script) => script.length > 0)
    .map((script) => createHash("sha256").update(asParsed(script)).digest("base64"));

  const path = `/${relative(CLIENT_DIR, file).split(sep).join("/")}`.replace(/index\.html$/, "");
  const csp = policy([...new Set(hashes)]);
  rules.push(`${path}\n  Content-Security-Policy: ${csp}`);
  if (path !== "/") {
    rules.push(`${path.replace(/\/$/, "")}\n  Content-Security-Policy: ${csp}`);
  }
}

const headers = `# Generated by scripts/csp-headers.mjs. Do not edit.

/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()

/assets/*
  Cache-Control: public, max-age=31536000, immutable

${rules.join("\n\n")}
`;

const longest = Math.max(...headers.split("\n").map((line) => line.length));
if (longest > 2000) throw new Error(`A line in _headers has ${longest} characters. Cloudflare permits 2,000.`);
if (rules.length > 90) throw new Error(`_headers has ${rules.length} page rules. Cloudflare permits 100 rules in total.`);

writeFileSync(join(CLIENT_DIR, "_headers"), headers);
console.log(`Wrote ${CLIENT_DIR}/_headers with ${rules.length} page rules.`);
